import {load,save} from './storage.js';
import {uid} from './data.js';
import {standings,holeResult,holeNet,totals} from './scoring.js';
import {calculateBets} from './betting.js';
import {listen,parseVoice,speak} from './voice.js';
import {playerRoundSummary,resultAnnouncement,roundResult} from './results.js';

const BETS=[0,10,30,50,100,150,200];
let state=load(), view=state.activeRound?'live':'setup', selectedHistory=null, playerView=null, historyPlayer='', historyMonth='';
const app=document.querySelector('#app');
const name=p=>p.displayName||p.nickname||p.fullName;
const initials=p=>name(p).split(/\s+/).map(x=>x[0]).slice(-2).join('').toUpperCase();
const pairKey=(a,b)=>[a,b].sort().join('|');
const money=n=>`${n<0?'−':'+'}₱${Math.abs(n)}`;
function persist(){save(state);}
function nav(){return `<header class="topbar"><a class="brand">⚑ <span>Caddie</span></a><nav>${[['setup','New round'],['live','Live round'],['players','Players'],['history','History']].map(([id,label])=>`<button data-view="${id}" class="${view===id?'active':''}">${label}</button>`).join('')}</nav></header>`;}
function shell(content){app.innerHTML=`${nav()}<main class="content">${content}</main>`;app.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;selectedHistory=null;render();});}
function setupView(){
 const course=state.courses[0], active=state.players.filter(p=>p.active!==false);
 const selected=active.filter(p=>p._selected!==false).slice(0,4); if(selected.length<2)active.slice(0,2).forEach(p=>p._selected=true);
 const pairs=[];for(let i=0;i<selected.length;i++)for(let j=i+1;j<selected.length;j++){const a=selected[i],b=selected[j],saved=state.agreements[pairKey(a.id,b.id)]||{giverId:a.id,receiverId:b.id,strokesPerNine:0};pairs.push({a,b,saved});}
 shell(`<section class="page-head"><p class="eyebrow">ROUND SETUP</p><h1>Set up today's barkada</h1><p>Choose players, fair strokes, and quick bet amounts.</p></section>
 <section class="card pad"><h2>Players</h2><div class="chips">${active.map(p=>`<label class="check-chip"><input type="checkbox" data-player="${p.id}" ${p._selected!==false?'checked':''}>${name(p)}</label>`).join('')}</div></section>
 <section class="card pad"><div class="section-title"><div><h2>Custom Barkada strokes</h2><p>Direction and strokes are independent for every pair.</p></div></div><div class="agreements">${pairs.map(({a,b,saved})=>`<article class="agreement" data-pair="${pairKey(a.id,b.id)}"><strong>${name(a)} ↔ ${name(b)}</strong><div class="agreement-fields"><label>Giver<select class="giver"><option value="${a.id}" ${saved.giverId===a.id?'selected':''}>${name(a)}</option><option value="${b.id}" ${saved.giverId===b.id?'selected':''}>${name(b)}</option></select></label><label>Receiver<input class="receiver" readonly value="${name(saved.giverId===a.id?b:a)}" data-id="${saved.giverId===a.id?b.id:a.id}"></label><label>Strokes / nine<input class="strokes" type="number" min="0" max="9" value="${saved.strokesPerNine||0}"></label></div><label class="save-default"><input type="checkbox"> Save as new default</label></article>`).join('')}</div></section>
 <section class="card pad"><h2>Bet amounts</h2><p>₱0 disables a bet.</p>${[['hole','Per hole'],['front','Front nine'],['back','Back nine'],['medal','Medal / overall'],['birdie','Birdie'],['sandy','Sandy par']].map(([key,label])=>`<fieldset class="bet-field"><legend>${label}</legend><div class="amounts">${BETS.map(n=>`<label><input type="radio" name="${key}" value="${n}" ${n===0?'checked':''}><span>₱${n}</span></label>`).join('')}</div></fieldset>`).join('')}</section><button id="start" class="primary sticky-action">START ROUND</button>`);
 document.querySelectorAll('[data-player]').forEach(x=>x.onchange=()=>{state.players.find(p=>p.id===x.dataset.player)._selected=x.checked;render();});
 document.querySelectorAll('.giver').forEach(sel=>sel.onchange=()=>{const card=sel.closest('.agreement'),ids=card.dataset.pair.split('|'),receiver=ids.find(id=>id!==sel.value),p=state.players.find(x=>x.id===receiver);card.querySelector('.receiver').value=name(p);card.querySelector('.receiver').dataset.id=receiver;});
 document.querySelector('#start').onclick=()=>{const ps=state.players.filter(p=>p.active!==false&&p._selected!==false).slice(0,4);if(ps.length<2)return alert('Choose at least two players.');const customAgreements=[];document.querySelectorAll('.agreement').forEach(card=>{const a={giverId:card.querySelector('.giver').value,receiverId:card.querySelector('.receiver').dataset.id,strokesPerNine:Math.max(0,+card.querySelector('.strokes').value||0)};customAgreements.push(a);if(card.querySelector('.save-default input').checked)state.agreements[card.dataset.pair]=a;});const bets=Object.fromEntries(['hole','front','back','medal','birdie','sandy'].map(k=>[k,+document.querySelector(`input[name="${k}"]:checked`).value]));bets.medalMode='net';state.activeRound={id:uid('round'),date:new Date().toISOString(),course:structuredClone(course),holes:course.holeCount,playerIds:ps.map(p=>p.id),playerSnapshots:structuredClone(ps),handicapMode:'custom',customAgreements,bets,scores:{},completedHoles:[],currentHole:1,status:'active'};persist();view='live';render();};
}
function livelyHole(r,n){const result=holeResult(r,n);if(!result)return '';if(result.tied)return `Hole ${n} is tied!`;const p=result.winners[0].player,entry=r.scores[n][p.id],hole=r.course.holes[n-1];if(entry.score<hole.par)return `Birdie for ${name(p)}! What a hole!`;return n%2?`${name(p)} gets the hole!`:`${name(p)} takes Hole ${n}!`;}
function liveView(){const r=state.activeRound;if(!r){view='setup';return setupView();}if(r.status==='complete')return resultsView(r);const n=r.currentHole,h=r.course.holes[n-1],entries=r.scores[n]||{};r.playerSnapshots.forEach(p=>{entries[p.id]??={score:h.par,sandy:false};});r.scores[n]=entries;
 const rows=standings(r),bets=calculateBets(r);shell(`<section class="hole-banner"><div><small>CURRENT HOLE</small><strong>${n}</strong></div><div><b>PAR ${h.par}</b><span>Handicap index ${h.index}</span></div></section><div id="announcement" class="announcement" aria-live="polite">${r.lastAnnouncement||'Ready for the next hole.'}</div>
 <section class="voice-card"><button id="mic" class="mic-button" aria-label="Record scores">🎙</button><div><strong id="voiceTitle">Tap to record scores</strong><span id="transcript">Try “Dodong birdie, Raymond five”</span></div></section>
 <div class="live-grid"><section class="card quick"><div class="section-title"><div><p class="eyebrow">FAST ENTRY</p><h2>Quick Score</h2></div><b>Hole ${n}</b></div>${r.playerSnapshots.map(p=>`<article class="quick-player"><div class="player-label"><span class="avatar" style="--avatar:${p.color}">${initials(p)}</span><strong>${name(p)}</strong><label><input type="checkbox" class="sandy" data-id="${p.id}" ${entries[p.id].sandy?'checked':''}> Sandy</label></div><div class="stepper"><button class="minus" data-id="${p.id}" aria-label="Decrease ${name(p)} score">−</button><input data-score="${p.id}" inputmode="numeric" value="${entries[p.id].score}" aria-label="${name(p)} score"><button class="plus" data-id="${p.id}" aria-label="Increase ${name(p)} score">+</button></div></article>`).join('')}<button id="saveHole" class="primary save-hole">SAVE HOLE</button></section>
 <aside><section class="card pad"><h2>Live leaderboard</h2><p>Net standings · through ${r.completedHoles.length} holes</p>${rows.map((x,i)=>`<div class="standing"><b>${i+1}. ${name(x.player)}</b><span>Gross ${x.gross} · Net ${x.net}</span><strong>${x.toPar>0?'+':''}${x.toPar}</strong></div>`).join('')}</section><section class="card pad"><h2>Betting</h2>${r.playerSnapshots.map(p=>`<div class="standing"><span>${name(p)}</span><strong class="${bets.ledger[p.id]>=0?'positive':'negative'}">${money(bets.ledger[p.id])}</strong></div>`).join('')}</section></aside></div>`);
 document.querySelectorAll('.plus,.minus').forEach(b=>b.onclick=()=>{const input=document.querySelector(`[data-score="${b.dataset.id}"]`);input.value=Math.max(1,+input.value+(b.classList.contains('plus')?1:-1));});
 document.querySelector('#mic').onclick=()=>{const button=document.querySelector('#mic');listen({onStart:()=>{button.classList.add('listening');document.querySelector('#voiceTitle').textContent='Listening…';},onText:(text,meta)=>{document.querySelector('#transcript').textContent=text;const parsed=parseVoice(text,r.playerSnapshots,h.par);parsed.entries.forEach(e=>document.querySelector(`[data-score="${e.playerId}"]`).value=e.score);if(meta.final&&!parsed.entries.length)document.querySelector('#voiceTitle').textContent='No usable score — tap to retry';},onError:m=>{button.classList.remove('listening');document.querySelector('#voiceTitle').textContent=m;},onEnd:()=>button.classList.remove('listening')});};
 document.querySelector('#saveHole').onclick=()=>{r.playerSnapshots.forEach(p=>{entries[p.id]={score:Math.max(1,+document.querySelector(`[data-score="${p.id}"]`).value||h.par),sandy:document.querySelector(`.sandy[data-id="${p.id}"]`).checked};});if(!r.completedHoles.includes(n))r.completedHoles.push(n);const announcement=livelyHole(r,n);r.lastAnnouncement=announcement;speak(announcement,state.settings.speech);if(n===9){const front=nineAnnouncement(r,1,9,'front nine');r.lastAnnouncement=front;speak(front,state.settings.speech);}if(n===r.holes){r.status='complete';r.finalAnnouncement=resultAnnouncement(r);r.betResults=calculateBets(r);state.history.unshift(structuredClone(r));state.activeRound=r;speak(r.finalAnnouncement,state.settings.speech);}else r.currentHole=n+1;persist();render();};
}
function nineAnnouncement(r,start,end,label){const vals=r.playerSnapshots.map(p=>({p,n:r.course.holes.slice(start-1,end).reduce((s,h)=>s+holeNet(r,p,h,r.scores[h.number][p.id]).score,0)}));const low=Math.min(...vals.map(x=>x.n)),wins=vals.filter(x=>x.n===low);return wins.length>1?`And that's the ${label}! We have a tie!`:`And that's the ${label}! ${name(wins[0].p)} wins it!`;}
function resultsView(r){const result=roundResult(r),bets=r.betResults||calculateBets(r);shell(`<section class="result-hero"><p class="eyebrow">ROUND COMPLETE</p><h1>${result.tied?'Match tied':`${name(result.winners[0].player)} wins!`}</h1><p>${r.finalAnnouncement}</p><button id="repeat" class="primary">🔊 REPEAT ANNOUNCEMENT</button></section><section class="card pad"><h2>Final gross & net</h2>${result.rows.sort((a,b)=>a.net-b.net).map(x=>`<div class="standing"><b>${name(x.player)}</b><span>Gross ${x.gross} · Net ${x.net}</span><strong>${result.winners.some(w=>w.player.id===x.player.id)?result.tied?'TIED':'WINNER':''}</strong></div>`).join('')}</section><section class="card pad"><h2>Settlement</h2>${bets.settlement.length?bets.settlement.map(s=>`<p>${name(r.playerSnapshots.find(p=>p.id===s.from))} pays ${name(r.playerSnapshots.find(p=>p.id===s.to))} <b>₱${s.amount}</b></p>`).join(''):'<p>No payment due.</p>'}</section><button id="done" class="secondary">Back to history</button>`);document.querySelector('#repeat').onclick=()=>speak(r.finalAnnouncement,true);document.querySelector('#done').onclick=()=>{state.activeRound=null;persist();view='history';render();};}
function historyView(){const rounds=state.history.filter(r=>(!historyPlayer||r.playerIds.includes(historyPlayer))&&(!historyMonth||r.date.slice(0,7)===historyMonth));if(selectedHistory){const r=state.history.find(x=>x.id===selectedHistory);return detailView(r);}shell(`<section class="page-head"><p class="eyebrow">PERFORMANCE ARCHIVE</p><h1>Round History</h1></section><section class="filters"><label>Player<select id="historyPlayer"><option value="">All players</option>${state.players.map(p=>`<option value="${p.id}" ${historyPlayer===p.id?'selected':''}>${name(p)}</option>`).join('')}</select></label><label>Month<input id="historyMonth" type="month" value="${historyMonth}"></label></section><div class="history-list">${rounds.length?rounds.map(r=>{const summary=historyPlayer?playerRoundSummary(r,historyPlayer):null,result=roundResult(r),lead=summary||result?.rows[0];return `<button class="history-card" data-round="${r.id}"><span><b>${new Date(r.date).toLocaleDateString(undefined,{month:'long',day:'numeric',year:'numeric'})}</b><strong>${r.course.name}</strong><small>${r.holes} holes</small></span><span><b>Gross ${lead?.gross??'—'} · Net ${lead?.net??'—'}</b><em>${summary?.status||(result?.tied?'TIED':'WINNER')}</em></span></button>`;}).join(''):'<div class="empty">No rounds match these filters.</div>'}</div>`);historyPlayer=document.querySelector('#historyPlayer').value;document.querySelector('#historyPlayer').onchange=e=>{historyPlayer=e.target.value;render();};document.querySelector('#historyMonth').onchange=e=>{historyMonth=e.target.value;render();};document.querySelectorAll('[data-round]').forEach(b=>b.onclick=()=>{selectedHistory=b.dataset.round;render();});}
function detailView(r){const result=roundResult(r),bets=r.betResults||calculateBets(r);shell(`<button id="back" class="back">← Round history</button><section class="page-head"><h1>${r.course.name}</h1><p>${new Date(r.date).toLocaleDateString()} · ${r.holes} holes</p></section><section class="card scorecard-wrap"><table><thead><tr><th>Hole</th>${r.course.holes.slice(0,r.holes).map(h=>`<th>${h.number}</th>`).join('')}<th>Out</th><th>In</th><th>Total</th></tr></thead><tbody>${r.playerSnapshots.flatMap(p=>{const gross=r.course.holes.slice(0,r.holes).map(h=>r.scores[h.number]?.[p.id]?.score??'—'),net=r.course.holes.slice(0,r.holes).map(h=>r.scores[h.number]?.[p.id]?holeNet(r,p,h,r.scores[h.number][p.id]).score:'—'),t=totals(r,p);return [`<tr><th>${name(p)} Gross</th>${gross.map(x=>`<td>${x}</td>`).join('')}<td>${gross.slice(0,9).reduce((a,b)=>a+(+b||0),0)}</td><td>${gross.slice(9).reduce((a,b)=>a+(+b||0),0)}</td><td><b>${t.gross}</b></td></tr>`,`<tr class="net-row"><th>${name(p)} Net</th>${net.map(x=>`<td>${x}</td>`).join('')}<td>${net.slice(0,9).reduce((a,b)=>a+(+b||0),0)}</td><td>${net.slice(9).reduce((a,b)=>a+(+b||0),0)}</td><td><b>${t.net}</b></td></tr>`]}).join('')}</tbody></table></section><section class="card pad"><h2>Result & settlement</h2><p>${r.finalAnnouncement}</p>${bets.settlement.map(s=>`<p>${name(r.playerSnapshots.find(p=>p.id===s.from))} → ${name(r.playerSnapshots.find(p=>p.id===s.to))}: ₱${s.amount}</p>`).join('')||'<p>No payment due.</p>'}${r.finalAnnouncement?'<button id="repeat" class="secondary">Repeat announcement</button>':''}</section>`);document.querySelector('#back').onclick=()=>{selectedHistory=null;render();};document.querySelector('#repeat')?.addEventListener('click',()=>speak(r.finalAnnouncement,true));}
function playersView(){const p=state.players.find(x=>x.id===playerView)||state.players[0],items=state.history.filter(r=>r.playerIds.includes(p.id)&&(!historyMonth||r.date.slice(0,7)===historyMonth)).map(r=>({r,s:playerRoundSummary(r,p.id)})),wins=items.filter(x=>x.s.status==='Winner').length,gross=items.map(x=>x.s.gross),net=items.map(x=>x.s.net);shell(`<section class="page-head"><p class="eyebrow">PLAYER PERFORMANCE</p><h1>${name(p)}</h1></section><div class="filters"><label>Player<select id="profilePlayer">${state.players.map(x=>`<option value="${x.id}" ${p.id===x.id?'selected':''}>${name(x)}</option>`).join('')}</select></label><label>Month<input id="historyMonth" type="month" value="${historyMonth}"></label></div><section class="stats">${[['Total rounds',items.length],['Wins',wins],['Win percentage',items.length?`${Math.round(wins/items.length*100)}%`:'—'],['Average gross',gross.length?(gross.reduce((a,b)=>a+b,0)/gross.length).toFixed(1):'—'],['Average net',net.length?(net.reduce((a,b)=>a+b,0)/net.length).toFixed(1):'—'],['Best gross',gross.length?Math.min(...gross):'—']].map(([l,v])=>`<div class="card"><span>${l}</span><strong>${v}</strong></div>`).join('')}</section><section class="card pad"><h2>Recent rounds</h2>${items.map(({r,s})=>`<div class="standing"><span><b>${new Date(r.date).toLocaleDateString()}</b><small>${r.course.name}</small></span><span>Gross ${s.gross} · Net ${s.net}</span><strong>${s.status.replace('Did not win','LOSS')}</strong></div>`).join('')||'<p>No rounds in this period.</p>'}</section>`);document.querySelector('#profilePlayer').onchange=e=>{playerView=e.target.value;render();};document.querySelector('#historyMonth').onchange=e=>{historyMonth=e.target.value;render();};}
function render(){if(view==='setup')setupView();else if(view==='live')liveView();else if(view==='history')historyView();else playersView();persist();}
render();
